Change output variable name in weight_signal
Error: global name 'x' was not defined in weight_signal
In weight_signal input variable was defined as data but in the output was definde as x.